### ISSUE TITLE
Regarding the Use of GPU Memory

### ISSUE THREAD

**Issue by sun2ot** [hanliu95/MetaMMF#1]
Thank you for your contributions in the field of multimodal recommendation. I would like to know on what GPU memory is your model trained?  

I used a dataset with the same format as `data_stample`, but smaller than TikTok in your paper, and still prompted CUDA out of memory. My GPU is A30 (24G).

**Comment by sun2ot** [comment]
user num: 38403
item num: 51937
v_feat dim: 16
t_feat dim: 16

And the model `Tried to allocate 101.44 GiB` ?

**Comment by hanliu95** [comment]
Thank you for your question. Increasing the value of the parameter
“indices_or_sections” in line 22 of GCN_model.py can solve this problem.

sun2ot ***@***.***> 于2024年10月29日周二 10:17写道：

**Comment by sun2ot** [comment]
Thank you very much for your reply!💗
